### ISSUE TITLE
Config-File darf nur im config Ordner liegen

### ISSUE THREAD

**Issue by patVog** [BOSWatch/BW3-Core#1]
Aktuell darf ein Config-File nur im config Ordner liegen und es sind nur relative Pfade zu diesem möglich. Absolute Pfade werden nicht unterstützt.

Üblich ist eigentlich, dass der absolute Pfad bzw. der Pfad relativ zum CWD verwendet werden kann.
Dies hat den Vorteil, dass die (eigene, angepasste) Config außerhalb des Repos liegen kann.

Falls diese Änderung so OK wäre, würde ich das so abändern.

**Comment by Schrolli91** [comment]
da es bei BOSWatch 3 wieder so sein wird, dass die configs so bennant sind `template.server.ini` und Sie zum Betrieb sowieso umbenannt werden sollten, macht es nichts aus, wenn die Files im Repo liegen, da sie bei einen Update nicht überschrieben werden.

Oder habe ich dich da falsch verstanden?

**Comment by Schrolli91** [comment]
Wie hast du dir eine Umsetzung absoluter Pfadangaben vorgestellt?

**Comment by patVog** [comment]
Man müsste nur "paths.CONFIG_PATH + " entfernen. Und vielleicht noch den Pfad checken, ob er valide ist.

**Comment by Schrolli91** [comment]
gerne kannst du das ganze umsetzen und per Pul-Req einbringen, Feinheiten können wir dann direkt da diskutieren

**Comment by Schrolli91** [comment]
@patVog konntest du das ganze bereits umsetzen?

**Comment by Schrolli91** [comment]
Ansatz wird überdacht und später angepasst
