### ISSUE TITLE
Dokumentation Offline

### ISSUE THREAD

**Issue by Rossibrother** [BOSWatch/BW3-Core#106]
Hey wie sieht es mit der Doku aus? Gibt es eine ausweisch Doku?

**Comment by janspeller** [comment]
Die sollte eigentlich garnicht weg sein, da scheint beim bauen was schief gelaufen zu sein, ich gucke mir das einmal an

**Comment by janspeller** [comment]
@Schrolli91 Der CNAME für docs.boswatch.de liegt auf https://boswatch.github.io/, das hat ja sonst eigentlich funktioniert, hattest du da was umgestellt?
Würde sonst ggf. ne Weiterleitung auf /BW3-Core einrichten.

@Rossibrother Zwischenzeitig ist die Doku über https://boswatch.github.io/BW3-Core/ zu erreichen.

**Comment by Rossibrother** [comment]
Alles klar Danke

**Comment by Schrolli91** [comment]
@janspeller nein, ich wüsste nicht, dass ich in letzter Zeit irgendwo rumgeschraubt habt.

Weiterleitung macht allerdings Sinn - denke da hat Github was geändert.
Die haben wohl früher automatisch weitergeleitet wenn es nur ein GH-Pages Repo gab.

**Comment by janspeller** [comment]
@Schrolli91 Kannst du das irgendo im Project umstellen? Sonst baue ich einfach die Weiterleitung mit ein. Cloudflare hat da ja die Page Rules für.

Wobei https://docs.boswatch.de/BW3-Core/ dann eigenltich funktionieren sollte, oder?

**Comment by Schrolli91** [comment]
@janspeller Hast du schon was gemacht? Wenn nein, hab ichs wohl "aus versehen" repariert :-D

Es hatte den Custom DNS Eintrag für die Domain aus dem Projekt raus gehauen. An der Config war ich aber sicher Monate nicht mehr dran. Muss also ein GH Problem sein.

**Comment by janspeller** [comment]
@Schrolli91 Du hast es scheinbar gefixed, ich hatte noch nichts gemacht :D

Vor n Wochen klappte docs.boswatch.de noch - scheint also Github gewesen zu sein, dann passt das hier ja :D

@Rossibrother Nun geht docs.boswatch.de auch wieder, danke für den Heads-Up.
