### ISSUE TITLE
Komische Ausgaben

### ISSUE THREAD

**Issue by Rossibrother** [BOSWatch/BW3-Core#108]
Hey, ich habe das problem das ich nur solche Ausgaben bekomme:

JuB- >t< ETB >< HT >< US >lh< FS >pp< SI >vTUQ< DEL >.g< VT >)Y.< SYN >äk2`O< EM >6Ls*< SI >#R$,nryzW< CR >< SI >< DC2 >9< LF >Äkim< HT >< FS >< SOH >R$< EM >:< CR >O z< SUB >W< CR >eadd< EM >g< US >< DC1 >< DC2 >< CAN >

< CAN >

< DLE >

kann mir jemand helfen?

sind sie vllt noch verschlüsselt?

**Comment by janspeller** [comment]
Das sieht mir sehr stark nach Verschlüsselung aus, bei uns im Kreis ist es ähnlich (RD ist verschlüsselt, FW nicht).
Boswatch unterstützt zZt. keine Entschlüsselung der Nachrichten.

**Comment by Rossibrother** [comment]
Hey ich hab mal nach geforscht, ich glaube das dass Pocsag nicht übersetzt wird, hat jemand einen idee woran das liegen könnte?

**Comment by janspeller** [comment]
Was meinst du mit “übersetzt”?

**Comment by Rossibrother** [comment]
dekodiert

**Comment by janspeller** [comment]
Natürlich wird das dekodiert, funktioniert bei mir Prima. Die Dekodierung erfolgt via Multimon, welches ja als Unterprozess des Clients läuft.
Die Nachricht aus der ursprünglichen Issue-Description sieht mir (wie schon beschrieben) sehr nach einer Verschlüsselten Nachricht aus. bist du dir sicher, dass in eurem Alarmierungs-Gebiet keine Verschlüsselung verwendet wird?

Swissphone IDEA, BosKrypt, … wären Verschlüsselungen die dann in den Pagern selber noch wieder entschlüsselt werden, das sieht mir ehrlich gesagt stark danach aus.

**Comment by Schrolli91** [comment]
Sieht für mich auch nach Encryption aus - da können wir leider nichts dran machen.
