### ISSUE TITLE
Install Fehler auf Debian GNU/Linux 12 (bookworm) aarch64

### ISSUE THREAD

**Issue by Editfusee** [BOSWatch/BW3-Core#113]
Wollte mal BW3-Core auf meinen RasberryPi4 Debian 12 installieren. Bekomme aber folgenden Fehler bei "download GIT and other stuff.........."

apt-get -y install git cmake build-essential libusb-1.0 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qt5-default libpulse-dev libx11-dev sox >> ${boswatch_install_path}/setup_log.txt 2>&1

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libusb-1.0-0-dev' for regex 'libusb-1.0'
Note, selecting 'libusb-1.0-doc' for regex 'libusb-1.0'
Note, selecting 'libusb-1.0-0' for regex 'libusb-1.0'
Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt5-default' has no installation candidate

**Comment by wattenre** [comment]
As described in #62, you have to update the install.sh script. qt5... is not available in your OS, you have to use qt6...


Maybe the names of the packages have changed, so changing qt5 to qt6 is not enough. If it is the case, try qt6-base-dev instead qt5-default or search for it. 

Please let us know, what changes you made to get it running on your system.

**Comment by Editfusee** [comment]
Vielen Dank, hat funktioniert!
