### ISSUE TITLE
Documentation seems to be offline

### ISSUE THREAD

**Issue by janspeller** [BOSWatch/BW3-Core#116]
@Schrolli91 The Documentation seems to be offline, can you look into the GitHub Pages Settings?

![grafik](https://github.com/BOSWatch/BW3-Core/assets/27723865/4b388cc8-1159-4db7-b3ca-392ab7005e3d)

**Comment by Schrolli91** [comment]
I'm not totally sure what's going on here.
Over the GH Pages link it's reachable: https://boswatch.github.io/BW3-Core/

Looks like, there was a change from github and now the DNS name is pointing to a wrong url
![image](https://github.com/BOSWatch/BW3-Core/assets/6043382/785e0109-e718-4d23-a5ae-b6b067a2e719)

Problem is, that i have no access to this Domain Settings my self ...

The docs domain isn't listed in the GH pages settings of this repo.
If i would try to add this custom domain to the repo, i will get this:

> The custom domain `docs.boswatch.de` is already taken. If you are the owner of this domain, check out https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages for information about how to verify and release this domain.

**Comment by janspeller** [comment]
The CNAME seems to be correct, I think the Domain is missing the TXT record.

If you mail the Records to me I can put them into the DNS. I think you forgot that I took over the Domain and Hosting for Mattermost😅

**Comment by Schrolli91** [comment]
Oh - yes i forgot this fact :-D
Cause the domain owner changed to often :-D

I will send you the necessary records tomorrow.

**Comment by Schrolli91** [comment]
I have sent you the DNS Record configuration via Mail.
Please let me know if it's set that i can verify the domain via github.

**Comment by Schrolli91** [comment]
Still won't work - but I have no idea what's going wrong here.

Domain is verfied at the ORG
![image](https://github.com/BOSWatch/BW3-Core/assets/6043382/e14483e0-62f2-4cf2-af59-df2b7f4ed073)

But if i want to add it in the repo here, i will get:
> The custom domain `docs.boswatch.de` is already taken. 

In the GH docs there is something mentioned about a 7 days duration time:
> beachte, dass der Prozess zur Freigabe der Domäne von ihrem derzeitigen Standort sieben Tage dauert.

Maybe we have to wait for completion here? I don't know... :-D

**Comment by Schrolli91** [comment]
Pages are back online now.
@janspeller Thanks for reporting the issue and help with the DNS record

Sidenode:
After waiting some time, i was able to add the domain.
So the part of the GH docs above seems to be correct.
