### ISSUE TITLE
Regex Filter

### ISSUE THREAD

**Issue by Tweak64** [BOSWatch/BW3-Core#119]
Ich habe in der Server.yaml den Regexfilter so konfiguriert:
  - type: module
    res: filter.regexFilter
    config:
       - name: "Ricfilter"
          checks:
              - field: ric
                 regex: "1234567,7654321,9876543,2345678"

Da ich keine Dokumentation gefunden habe, habe ich es einfach mal versucht. Grundsätzlich ist Einrückung etc. korrekt, da der Filter auch angewendet wird. Allerdings kommt keine Ric durch. Die Besonderheit ist, dass es viele unterschiedliche Rics sind, die nicht unbedingt einem Schema folgen. Ist es möglich, so wie im "alten" BW eine Liste an Rics zu übergeben, sodass nur die benannten Rics durchkommen? Wenn nicht, müsste ich im nachgelagerten http Plugin in der aufgerufenen PHP nen Filter schreiben.

**Comment by janspeller** [comment]
Versuch mal die Rics mit | zu trennen, dass ist regex fuer “oder”.

**Comment by wattenre** [comment]
Hi, dein Regex stimmt so nicht, probiere es mal so:
```
regex: "(0000001|0000002|0000003)"
```

**Comment by Tweak64** [comment]
Wie krass schnell seid ihr denn bitte?! :D 
Habe es angepasst und werde bei Erfolg das Issue schließen. Wie der Filter aufgebaut wird, ist für den ein oder anderen sicher im Nachgang auch ein wertvolle Info.

**Comment by wattenre** [comment]
[Hier](https://docs.boswatch.de/modul/regex_filter.html) ist die offizielle Doku, da könnte man natürlich das Beispiel mit der Liste mit aufnehmen, dazu gerne ein Pull Request für [diese Datei](https://github.com/BOSWatch/BW3-Core/blob/develop/docu%2Fdocs%2Fmodul%2Fregex_filter.md) stellen.

**Comment by Schrolli91** [comment]
@Tweak64 @wattenre 
Doku angepasst ;-)
https://docs.boswatch.de/modul/regex_filter.html#konfiguration

**Comment by Tweak64** [comment]
Doku angepasst und direkt offline genommen? ;) Scheint derzeit down zu sein.

**Comment by Schrolli91** [comment]
@Tweak64 danke für den Hinweis :-D

Githaub mal wieder -.-
![image](https://github.com/BOSWatch/BW3-Core/assets/6043382/d71b1b3b-75c0-4636-803e-1e5155478863)

@janspeller Und es geht schon wieder los :-D
Müssen wir mal drauf achten ob es offline bleibt ...
