### ISSUE TITLE
 [RESOLVED] mysql plugin Plugin not found

### ISSUE THREAD

**Issue by BOSFF** [BOSWatch/BW3-Core#121]
Hallo zusammen,
ich hab es nach langem hin und her geschafft BosWatch3 zum laufen zu bekommen (nur mit der Hilfe von einem Kollegen)

Jetzt bin ich gerade dran das MySQL Plugin zum laufen zu bekommen.
Ich habe schon mysql-connector-python mit pip installiert.
Es kommt aber immer beim Start der server .py der Fehler "plugin not found: mysql" 
Das plugin hab ich in den Ordner heruntergeladen.
Kann mir da jemand helfen?
Anbei der Fehler und die server.yaml

*EDIT* Der Telegram bot funtioniert einwandfrei.
Es lässt sich auch alles wie gewohnt starten, wenn ich das mysql plugin raus kommentiere

`/opt/boswatch3 $ sudo python3 bw_server.py -c server.yaml
29.05.2024 19:57:54,072 - bw_server       [DEBUG   ]
29.05.2024 19:57:54,073 - bw_server       [DEBUG   ] ######################## NEW LOG ############################
29.05.2024 19:57:54,073 - bw_server       [DEBUG   ] BOSWatch server has started ...
29.05.2024 19:57:54,073 - bw_server       [DEBUG   ] Import python modules
29.05.2024 19:57:54,078 - bw_server       [DEBUG   ] - argparse
29.05.2024 19:57:54,079 - bw_server       [DEBUG   ] - queue
29.05.2024 19:57:54,079 - bw_server       [DEBUG   ] - time
29.05.2024 19:57:54,079 - bw_server       [DEBUG   ] Import BOSWatch modules
29.05.2024 19:57:54,119 - configYaml      [DEBUG   ] - boswatch.configYaml loaded
29.05.2024 19:57:54,120 - server          [DEBUG   ] - boswatch.network.server loaded
29.05.2024 19:57:54,121 - packet          [DEBUG   ] - boswatch.packet loaded
29.05.2024 19:57:54,128 - version         [DEBUG   ] - boswatch.utils.version loaded
29.05.2024 19:57:54,128 - header          [DEBUG   ] - boswatch.utils.header loaded
29.05.2024 19:57:54,129 - broadcast       [DEBUG   ] - boswatch.network.broadcast loaded
29.05.2024 19:57:54,131 - router          [DEBUG   ] - boswatch.router.router loaded
29.05.2024 19:57:54,132 - route           [DEBUG   ] - boswatch.router.route loaded
29.05.2024 19:57:54,132 - routerManager   [DEBUG   ] - boswatch.router.routerManager loaded
29.05.2024 19:57:54,133 - misc            [DEBUG   ] - boswatch.utils.misc loaded
29.05.2024 19:57:54,134 - header          [DEBUG   ] BOSWatch and environment information
29.05.2024 19:57:54,134 - header          [DEBUG   ] - Client version:   3.0.0
29.05.2024 19:57:54,134 - header          [DEBUG   ] - Server version:   3.0.0
29.05.2024 19:57:54,134 - header          [DEBUG   ] - Branch:           develop
29.05.2024 19:57:54,135 - header          [DEBUG   ] - Release date:     01.01.2019
29.05.2024 19:57:54,135 - header          [DEBUG   ] - Python version:   3.11.2
29.05.2024 19:57:54,135 - header          [DEBUG   ] - Python build:     ('main', 'Mar 13 2023 12:18:29')
29.05.2024 19:57:54,135 - header          [DEBUG   ] - System:           Linux
29.05.2024 19:57:54,145 - header          [DEBUG   ] - OS Version:       Linux-6.6.20+rpt-rpi-v8-aarch64-with-glibc2.36
29.05.2024 19:57:54,145 - header          [DEBUG   ]
29.05.2024 19:57:54,154 - configYaml      [DEBUG   ] load config file from: /opt/boswatch3/boswatch/../config/server.yaml
29.05.2024 19:57:54,162 - routerManager   [DEBUG   ] build routers
29.05.2024 19:57:54,162 - router          [DEBUG   ] [Router 1] add new router
29.05.2024 19:57:54,164 - wildcard        [DEBUG   ] - boswatch.wildcard loaded
29.05.2024 19:57:54,165 - pluginBase      [DEBUG   ] - plugin.pluginBase loaded
29.05.2024 19:57:54,907 - telegram        [DEBUG   ] - plugin.telegram loaded
29.05.2024 19:57:54,908 - pluginBase      [DEBUG   ] [plugin.telegram] onLoad()
/usr/local/lib/python3.11/dist-packages/telegram/ext/messagequeue.py:230: TelegramDeprecationWarning: MessageQueue in its current form is deprecated and will be reinvented in a future release. See https://github.com/python-telegram-bot/python-telegram-bot/issues/2139 for a list of known bugs.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/telegram/ext/messagequeue.py:94: TelegramDeprecationWarning: DelayQueue in its current form is deprecated and will be reinvented in a future release. See https://github.com/python-telegram-bot/python-telegram-bot/issues/2139 for a list of known bugs.
  warnings.warn(
queue
29.05.2024 19:57:54,910 - router          [DEBUG   ] [Router 1] add route: Telegram Plugin
29.05.2024 19:57:54,912 - routerManager   [ERROR   ] plugin not found: mysql
29.05.2024 19:57:54,912 - bw_server       [CRITICAL] Error while building routers
29.05.2024 19:57:54,912 - bw_server       [ERROR   ] BOSWatch interrupted by an error
29.05.2024 19:57:54,913 - bw_server       [DEBUG   ] Starting shutdown routine
29.05.2024 19:57:54,913 - bw_server       [DEBUG   ] BOSWatch server has stopped ...`

server:
  port: 8080
  name: BW3 Server        # name of the BW3 Server instance
  useBroadcast: no        # serve server ip on broadcast request

alarmRouter:
- Router 1

router:
- name: Router 1
  route:
#  - type: module
#    res: filter.modeFilter
#    name: Filter Fms/Zvei
#    config:
#      allowed:
#        - fms
#        - zvei
  - type: plugin
    name: Telegram Plugin
    res: telegram
    config:
      message_pocsag: "RIC:{RIC}{SRICT}\nAlarmtext:{MSG}"
      message_fms: "{MODE} {DIRT}: Fahrzeug {VEHC} Status {STAT}\nService {SERV}, Location {LOC}, Info {TACI}"
      botToken: "************************"
      chatIds:
        - "***************"

  - type: plugin
    name: mysql
    res: mysql
    config:
      host: localhost
      user: ***********
      password: **************
      database: einsätze
`
Grüße

**Comment by wattenre** [comment]
Erster Gedanke: Mit pip oder mit pip3 installiert? Du musst letzteres wählen, da BosWatch3 python3 nutzt.

**Comment by BOSFF** [comment]
> Erster Gedanke: Mit pip oder mit pip3 installiert? Du musst letzteres wählen, da BosWatch3 python3 nutzt.

Ich hätte es mit pip installiert und jetzt noch mal mit pip3 versucht. Der Fehler bleibt

**Comment by BOSFF** [comment]
Hallo zusammen,
Das Problem habe ich mit der Hilfe eines Nutzers gelöst bekommen.
Der Fehler war, dass ich die falsche Version des sql connectors installiert hatte.
mit `pip install my-sql-connector-python==8.0.23` funktioniert es.
zusätzlich bzw. zur Sicherheit habe ich noch den mariadb client installiert.
`sudo apt install mariadb-client`
Jetzt findet das Programm das Plugin.

**Comment by BOSFF** [comment]
Hallo zusammen,
ich habe gezwungener Maßen meinen PI neu aufsetzen müssen.
Ich habe versucht alles wieder so zu installieren, wie es vorher war. 
Das habe ich auch zum Teil hin bekommen. Jetzt habe ich aber wieder den selben fehler wie davor.
Das Plugin wird nicht gefunden. Ich habe alles so gemacht, wie es das letzte mal funktioniert hatte, jedoch klappt es dieses mal nicht. 

Kann mir da jemand helfen? Gibt es irgendwo einen ausführlichen Log? Wiel mit "plugin not found: mysql" kann ich nur wenig anfangen.

**Comment by BOSFF** [comment]
Hallo zusammen,
ich habe gezwungener Maßen meinen PI neu aufsetzen müssen.
Ich habe versucht alles wieder so zu installieren, wie es vorher war. 
Das habe ich auch zum Teil hin bekommen. Jetzt habe ich aber wieder den selben fehler wie davor.
Das Plugin wird nicht gefunden. Ich habe alles so gemacht, wie es das letzte mal funktioniert hatte, jedoch klappt es dieses mal nicht. 

Kann mir da jemand helfen? Gibt es irgendwo einen ausführlichen Log? Wiel mit "plugin not found: mysql" kann ich nur wenig anfangen.

Hier noch der Log Auszug davon:
`04.08.2024 16:42:29,516 - MainThread      configYaml      loadConfigFile     [DEBUG   ] load config file from: /opt/boswatch3/boswatch/../config/server.yaml
04.08.2024 16:42:29,566 - MainThread      routerManager   buildRouters       [DEBUG   ] build routers
04.08.2024 16:42:29,566 - MainThread      router          init           [DEBUG   ] [Router 1] add new router
04.08.2024 16:42:29,569 - MainThread      wildcard        <module>           [DEBUG   ] - boswatch.wildcard loaded
04.08.2024 16:42:29,569 - MainThread      moduleBase      <module>           [DEBUG   ] - module.moduleBase loaded
04.08.2024 16:42:29,569 - MainThread      descriptor      <module>           [DEBUG   ] - module.descriptor loaded
04.08.2024 16:42:29,570 - MainThread      moduleBase      init           [DEBUG   ] [module.descriptor] onLoad()
04.08.2024 16:42:29,570 - MainThread      wildcard        registerWildcard   [DEBUG   ] register new wildcard {RIC} for field: ric
04.08.2024 16:42:29,570 - MainThread      wildcard        registerWildcard   [DEBUG   ] register new wildcard {SRICT} for field: subricText
04.08.2024 16:42:29,570 - MainThread      router          addRoute           [DEBUG   ] [Router 1] add route: descriptor
04.08.2024 16:42:29,583 - MainThread      pluginBase      <module>           [DEBUG   ] - plugin.pluginBase loaded
04.08.2024 16:42:29,585 - MainThread      routerManager   buildRouters       [ERROR   ] plugin not found: mysql
04.08.2024 16:42:29,586 - MainThread      bw_server       <module>           [CRITICAL] Error while building routers
04.08.2024 16:42:29,586 - MainThread      bw_server       <module>           [ERROR   ] BOSWatch interrupted by an error
04.08.2024 16:42:29,587 - MainThread      bw_server       <module>           [DEBUG   ] Starting shutdown routine
04.08.2024 16:42:29,587 - MainThread      bw_server       <module>           [DEBUG   ] BOSWatch server has stopped ...`

**Comment by BOSFF** [comment]
Weil ich es selbst wieder vergessen hab dient der Kommentar dazu, denen Personen zu helfen, die an dem Plugin schon verzweifelt sind...
man muss den mariadb Client installieren.
Sowie den mysql connector.
Bei diesem reicht es nicht das einfach mit pip zu installieren.

`sudo pip3 install mysql-connector-python==8.0.23 --break-system-packages`

erst mit sudo funktioniert es. Keine Ahnung warum.
Auf jedenfall werden dann noch zwei Sachen installiert
