### ISSUE TITLE
queue nicht gefunden

### ISSUE THREAD

**Issue by Smeti1** [BOSWatch/BW3-Core#22]
Neu Aufgesetzt und erster Start:
```
sudo python bw_server.py
11.04.2020 12:05:36,888 - bw_server       [DEBUG   ]
11.04.2020 12:05:36,889 - bw_server       [DEBUG   ] ######################## NEW LOG ############################
11.04.2020 12:05:36,889 - bw_server       [DEBUG   ] BOSWatch server has started ...
11.04.2020 12:05:36,889 - bw_server       [DEBUG   ] Import python modules
11.04.2020 12:05:36,905 - bw_server       [DEBUG   ] - argparse
Traceback (most recent call last):
  File "bw_server.py", line 35, in <module>
    import queue
ImportError: No module named queue
```

Habe alles abgesucht "queue" ist wirklich nirgends zu finden
Auch bei bw_client.py die selbe Meldung

queue auskommentieren und es läuft weiter und hängt an einer anderen Stelle
-----------------------------------------------------------------------------------------------------
System: Raspberry Pi4, Debian Buster light

**Comment by janspeller** [comment]
Hast du das HTTP Plugin aktiviert?
Dies hat queue als Abhängigkeit.
Mit welcher Python Version führst du Boswatch aus?

**Comment by Schrolli91** [comment]
Welche Python Version wird genutzt?

**Comment by Schrolli91** [comment]
@janspeller evtl lässt sich da ja eine Abfrage implementieren, welche die genutzte Python Version beim Hochlauf prüft?
BW3 setzt ja auf Python 3 auf, im Gegensatz zum alten BW, welches noch unter Python 2.* lief

**Comment by Smeti1** [comment]
Hallo

 

Also es lief Python  Version 2.7.18 

Ich deinstalliere mal die Version und mache die Version 3 darauf

 

Version 3.7.3 ist jetzt Installiert

selber Fehler 

wenn ich den queue auskommentiere läuft es weiter bis :

 

 

 

Traceback (most recent call last):

  File "bw_client.py", line 41, in <module>

    from boswatch.configYaml import ConfigYAML

  File "/opt/boswatch/boswatch/configYaml.py", line 61

    def get(self, *args, default=None):

                               ^

SyntaxError: invalid syntax

 

ab Dienstag habe ich mehr Zeit mir das ganze genauer anzuschauen

Frohe Ostern wünsche ich dir und deiner Familie

 

Gruß Tom

 

 

 

Von: Bastian Schroll [mailto:notifications@github.com] 
Gesendet: Samstag, 11. April 2020 16:17
An: BOSWatch/BW3-Core
Cc: Smeti; Author
Betreff: Re: [BOSWatch/BW3-Core] queue nicht gefunden (#22)

 

@janspeller <https://github.com/janspeller>  evtl lässt sich da ja eine Abfrage implementieren, welche die genutzte Python Version beim Hochlauf prüft?
BW3 setzt ja auf Python 3 auf, im Gegensatz zum alten BW, welches noch unter Python 2.* lief

**Comment by janspeller** [comment]
@Schrolli91 für die Überprüfung vielleicht ein neues Issie?
Setz ich mich anchher auf jeden fall mal dran und gucke was möglich ist

**Comment by Smeti1** [comment]
Hallo

 

Also mit 

sudo python3 bw_client.py -c client.yaml

läuft faßt alles richtig durch beim RTL_FM hatte er den Path falsch der liegt nicht /usr/bin/rtl_fm sondern /usr/local/bin/rtl_fm

den multimon_ng muß ich jetzt mal suchen da stimmt der Path auch nicht /opt/multimon/multimon-ng oder habe ich den aus versehen gelöscht?

 

gruß Tom

 

 

 

Von: Jan Speller [mailto:notifications@github.com] 
Gesendet: Samstag, 11. April 2020 17:40
An: BOSWatch/BW3-Core
Cc: Smeti; Author
Betreff: Re: [BOSWatch/BW3-Core] queue nicht gefunden (#22)

 

@Schrolli91 <https://github.com/Schrolli91>  für die Überprüfung vielleicht ein neues Issie?
Setz ich mich anchher auf jeden fall mal dran und gucke was möglich ist

**Comment by Schrolli91** [comment]
Nein das mit den Pfaden kann durchaus sein, dass es nicht stimmt.
Sind die Pfade meiner dev-Maschine

**Comment by janspeller** [comment]
@Smeti1 Eventuell tuts ein `whereis multimon-ng`, dann braucht man nicht zu suchen :wink:

**Comment by Schrolli91** [comment]
@janspeller Guter Einwand - Vielleicht kann man ja sogar Bostwach dazu überreden, die binaries mit `whereis` selbst zu suchen? :-P

**Comment by Smeti1** [comment]
die Pfade müssen nicht drinnen sein in der client.yaml
es geht nur mit 
```
rtlPath: rtl_fm
mmPath: multimon-ng
```

**Comment by Schrolli91** [comment]
dann ist das hiermit ja erledigt
