### ISSUE TITLE
Zvei Tone - Platzhalter

### ISSUE THREAD

**Issue by KirschbaumP** [BOSWatch/BW3-Core#23]
Der Platzhalter "TONE" wird nicht durch die zugehörige 5-Ton-Folge ersetzt.
Das liegt vermutlich daran, dass die 5-Ton-Folge im [ZveiDecoder](https://github.com/BOSWatch/BW3-Core/blob/9eaa146f10d42832777743cca77f035376e54b9b/boswatch/decoder/zveiDecoder.py#L45) auf das Attribute mit dem Namen "zvei" gesetzt wird und in der Methode [replaceWildcards](https://github.com/BOSWatch/BW3-Core/blob/9eaa146f10d42832777743cca77f035376e54b9b/boswatch/wildcard.py#L92) versucht wird das Attribute "tone" zu verwenden.

**Comment by Schrolli91** [comment]
Da hast du absolut recht!
Das muss natürlich auch im Decoder `tone` heißen (https://github.com/BOSWatch/BW3-Core/blob/9eaa146f10d42832777743cca77f035376e54b9b/boswatch/decoder/zveiDecoder.py#L45)

Siehe Dokumentation: https://docs.boswatch.de/develop/packet.html#speziell-fur-zvei

Möchtest du die Anpassung direkt als Pull-Request einreichen?

**Comment by KirschbaumP** [comment]
> Möchtest du die Anpassung direkt als Pull-Request einreichen?

PR ist erstellt #24
