### ISSUE TITLE
Message-Queuing for Telegram

### ISSUE THREAD

**Issue by janspeller** [BOSWatch/BW3-Core#39]
The Telegram Bot Api is Rate-Limited to 30 Messages/s in general and 20 Messages/60s for groups/channels.

If the Bot hits these Limit, it may get a Error 429 as a callback and retry. To prevent CPU-Stressing, we should add queuing to the bot.

https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits

**Comment by Schrolli91** [comment]
PR #50 is ongoing - closed
