### ISSUE TITLE
My client crash with a loop

### ISSUE THREAD

**Issue by sm7tix** [BOSWatch/BW3-Core#44]
I have now all the logfiles and i can not find the reason for the crashes. 
Advice me what you need more to help me. 
[asla.log](https://github.com/BOSWatch/BW3-Core/files/4574935/asla.log)
[client.zip](https://github.com/BOSWatch/BW3-Core/files/4574963/client.zip)
[multimon-ng.zip](https://github.com/BOSWatch/BW3-Core/files/4574967/multimon-ng.zip)

**Comment by Schrolli91** [comment]
Hardware, OS, other Tools running? More info is always better ...

**Comment by sm7tix** [comment]
I have changed to a Raspberry Pi 3b+ and run Rasbian 5.4.35-v7+. I use linein from a usb soundcard. Just the bw3 server and client running on this Pi.

**Comment by Schrolli91** [comment]
which SDR Dongle and which USB Soundcard?

**Comment by sm7tix** [comment]
No dongle at all and a Chinese noname usb soundcard. I have got it to decode ones or twice but then something happens.

**Comment by Schrolli91** [comment]
Do you have this poblem only with line in or also with an sdr?
Maybe there's a alsa/performance problem at this point on a Raspi.
@janspeller can you also take a look into the logs, please?

**Comment by sm7tix** [comment]
I have not tried BW3 with sdr. I use BW2 on another Pi with sdr and it works great. I will try to reinstall and see it that helps. In log it looks like the arecord crash also with overrun and i dont know what it is.

**Comment by Schrolli91** [comment]
Can you try this maybe? https://www.raspberrypi.org/forums/viewtopic.php?t=52390

And thats also interesting
https://www.raspberrypi.org/forums/viewtopic.php?t=43738

**Comment by sm7tix** [comment]
now i am trying --buffer-size=192000 (10s) if i am correct. To much but it was a suggestion on net. Not so much alarm here so it will take a while to get an error.

**Comment by sm7tix** [comment]
No crash so far :) 3 alarms decoded. Buffersize seams to do the trick. Set 100000 now. 
I read that someone use ffmpeg, maybe better then arecord?

**Comment by sm7tix** [comment]
Today it crashed again. I increase buffer to 150000 now and start again.

**Comment by sm7tix** [comment]
I give up. Nothing seem to help.

**Comment by Schrolli91** [comment]
Looks like a general problem to me. I think on a machine with more power this will not happen.
But i have no idea whats the exact problem here and what we can do to fix that - maybe someone other has an idea for that.

**Comment by sm7tix** [comment]
Testing on a PI4 4GB now. Let you know if it works better.

**Comment by sm7tix** [comment]
Workoing longer on the PI4, a few days, then same thing happens. And the watchdog is just looping. I think the watchdog has to be rewritten to kill the whole client, wait for 2 seconds and then start all over. The PID thing now dont work for me at all. And to the watchdog you should be able to connect the plugins too, so when it trigger the watchdog it is possible to get a notification in Pushover for example.

**Comment by janspeller** [comment]
I finally had some time to look into this.
If you didn't already, you might try using arecord with ` --buffer-time=1000000` instead of `--buffer-size`.

According to the also manual, buffer-time is in microseconds, so 1000000 would be exactly 1 second.

**Comment by sm7tix** [comment]
Ok 

I have changed and started. The process manager need some work too
because it just loop. I have try to add a stop argument before try to
start again.

---
Med vänlig hälsning

Stefan Rydberg
0767-882514 

2020-06-07 23:20 skrev Jan Speller:

> I finally had some time to look into this.
> If you didn't already, you might try using arecord with --buffer-time=1000000 instead of --buffer-size. 
> 
> According to the also manual, buffer-time is in microseconds, so 1000000 would be exactly 1 second. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/BOSWatch/BW3-Core/issues/44#issuecomment-640281561
[2]

**Comment by Schrolli91** [comment]
> The process manager need some work too because it just loop.

What do you mean, exactly?

**Comment by sm7tix** [comment]
When the processmanager thinks that arecord or multimon is down it tries
to restart them, but then it ends up in a loop. I have not dig into this
but yesterday when the client crashed it filled up my sdcard with
logs.When i notised i empty the log folder and restart the client again.
I hope i explained it more clear now :D 

The client still works with the new settings. I hold my thumb.

---
Med vänlig hälsning

Stefan Rydberg
0767-882514 

2020-06-08 07:46 skrev Bastian Schroll:

>> The process manager need some work too because it just loop.
> 
> What do you mean, exactly? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/BOSWatch/BW3-Core/issues/44#issuecomment-640383022
[2]

**Comment by sm7tix** [comment]
> I finally had some time to look into this.
> If you didn't already, you might try using arecord with ` --buffer-time=1000000` instead of `--buffer-size`.
> 
> According to the also manual, buffer-time is in microseconds, so 1000000 would be exactly 1 second.

Still crash and filled up my sdcard. I had made some changes to the "watchdog" so maybe next time i can read the logs.

**Comment by sm7tix** [comment]
Still no luck. Crash and fill up sdcard. I will stay with BW2.

**Comment by Schrolli91** [comment]
@sm7tix maybe this is fixed with #64 from @janspeller ?

**Comment by sm7tix** [comment]
I am sorry but i cant try it out. No external soundcard available. 

---
Med vänlig hälsning

Stefan Rydberg

2021-01-08 20:33 skrev Bastian Schroll:

> @sm7tix [1] maybe this is fixed with #64 [2] from @janspeller [3] ? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].
 

Links:
------
[1] https://github.com/sm7tix
[2] https://github.com/BOSWatch/BW3-Core/pull/64
[3] https://github.com/janspeller
[4]
https://github.com/BOSWatch/BW3-Core/issues/44#issuecomment-756953358
[5]
