### ISSUE TITLE
Move start-mm to Class "InputBase"

### ISSUE THREAD

**Issue by b-watch** [BOSWatch/BW3-Core#48]
As discussed in PR #47, it would be better to move the basic of the mm-start to the InputBase.
After a little bit of thinking and testing, I would say, we should also move the config-settings "mmPath" and "mmChar" from "inputsource" to "decoder", maybe also rename them to just "path" and "char".
Before I begin with coding, I would like to get feedback on that, so would this be a way to do it?
Any other suggestions?

**Comment by Schrolli91** [comment]
> After a little bit of thinking and testing, I would say, we should also move the config-settings "mmPath" and "mmChar" from "inputsource" to "decoder", maybe also rename them to just "path" and "char".

Sounds good for me ...



> ... to move the basic of the mm-start to the InputBase.

Best place for that is the InputBase class in my opinion.  So we need a function to set the stdin of MM in the inoutsource class. The `addToQueue` method in the base can then also be private.

**Comment by Schrolli91** [comment]
Ich schliese mal da #49 jetzt läuft ...
closed because #49
