### ISSUE TITLE
Timestamp when server is offline

### ISSUE THREAD

**Issue by sm7tix** [BOSWatch/BW3-Core#56]
When the server is offline I would like the client to create the timestamp on its side, so when server goes online again and the client que is sending the timestamp will be the time the alarm was and not when the server goes online.

**Comment by sm7tix** [comment]
I think I have got it working. By enable --timestamp in inputBase.py 
`mmProc.addArgument("--timestamp")`
and in pocsagDecoder.py extract the timestamp and add the timestamp to the packet.  The the packet has the timestamp when it was received. Before it was None and the server added timestamp when it was received.

**Comment by Schrolli91** [comment]
I am not sure what this flag should change here. The decoder does not read the timestamp from multimon directy

The decoder creates a bwPacket and here the timestamp is generated.
https://github.com/BOSWatch/BW3-Core/blob/bd9228f0cf5e068da816afb941dd330cf5dfbe6d/boswatch/packet.py#L32

And after sending, the string representation of this packet is feeded to the constructer of the bwPacket and should be read from the packet.
https://github.com/BOSWatch/BW3-Core/blob/bd9228f0cf5e068da816afb941dd330cf5dfbe6d/boswatch/packet.py#L35

**Comment by sm7tix** [comment]
In my case the client didnt send timestamp before and the server created it because it was None. If the server was down and when the que arrived all alarm got time from server, not from client. With my new code i get a timestamp from client when it was received and
[pocsag-files.zip](https://github.com/BOSWatch/BW3-Core/files/5528738/pocsag-files.zip)

 not when server created timestamp. 
Hard to explain but for me it works now. My code is very bad but it works,

**Comment by Schrolli91** [comment]
it is not NONE or shouldn't be :-D
but the client will receive the packets from a MM-buffer at the moment, the client is reconnected and set the timestamp at this moment. That's a architecture problem in my opinion.

**Comment by sm7tix** [comment]
Ok. I like to have the time when multimon decode it, not when sending it.
Like you say, different taste. :)

Stefan Rydberg


Den 12 november 2020 08:14:54 skrev Bastian Schroll <notifications@github.com>:
