### ISSUE TITLE
Path to log point to /log when starting from systemd

### ISSUE THREAD

**Issue by sm7tix** [BOSWatch/BW3-Core#57]
When i use systemd to start boswatch3, i get an error that /log does not exist. After created that dir it start and puts the logs there. Usally the logs are in /opt/boswatch3/log. I use this script
[Unit]
Description=BOSWatch
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/boswatch3/bw_client.py -c client.yaml
Restart=on-abort

[Install]
WantedBy=multi-user.target

**Comment by janspeller** [comment]
You have to set the "WorkingDirectory" Flag to your boswatch directory :)

```
WorkingDirectory=/opt/boswatch3
```

and then do a

`sudo systemctl daemon-reload`

**Comment by sm7tix** [comment]
Ok.
Thanks
Med vänlig hälsning

Stefan Rydberg
0767-882514

Den 29 september 2020 09:21:05 skrev Jan Speller <notifications@github.com>:

**Comment by Schrolli91** [comment]
Problem fixed?

@sm7tix if it works, maybe you can provide an examle systemd service file for the docs?

**Comment by sm7tix** [comment]
Yes, it works. Serice look like this: 

[Unit]
Description=BOSWatch3
After=multi-user.target 

[Service]
Type=simple
WorkingDirectory=/opt/boswatch3
ExecStart=/usr/bin/python3 /opt/boswatch3/bw_client.py -c client.yaml
Restart=on-abort 

[Install]
WantedBy=multi-user.target 

---
Med vänlig hälsning

Stefan Rydberg
0767-882514 

2020-09-29 11:12 skrev Bastian Schroll:

> Problem fixed? 
> 
> @sm7tix [1] if it works, maybe you can provide an examle systemd service file for the docs? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/sm7tix
[2]
https://github.com/BOSWatch/BW3-Core/issues/57#issuecomment-700574857
[3]

**Comment by sm7tix** [comment]
Solved with the WorkingDirectory=/opt/boswatch3 in sthe service file for systemd.
