### ISSUE TITLE
Subric out of range in pocsagDecoder.py

### ISSUE THREAD

**Issue by sm7tix** [BOSWatch/BW3-Core#61]
If somehow the subric commes out of range, the client goes to shoutdown mode and stops. 
I dont use subric so i put 4 as default and then all runs fine again. Should be some check here that dump packets that are not correct.

**Comment by Schrolli91** [comment]
Why your subric goes "out of range"?
How is that possible?

**Comment by sm7tix** [comment]
I have no idea why.
Med vänlig hälsning

Stefan Rydberg
0767-882514

Den 12 november 2020 07:41:06 skrev Bastian Schroll <notifications@github.com>:

**Comment by Schrolli91** [comment]
And where? Do you have a log dump when this happens?

**Comment by sm7tix** [comment]
Sorry. I dont have more info.
Close it if you like.
Stefan Rydberg


Den 12 november 2020 08:11:56 skrev Bastian Schroll <notifications@github.com>:
