### ISSUE TITLE
plugin not found: telegram

### ISSUE THREAD

**Issue by dernippel** [BOSWatch/BW3-Core#63]
I'm currently stucking on configuring the telegram plugin.

routerManager says "[ERROR   ] plugin not found: telegram"

I already installed the telegram bot via "pip install python-telegram-bot".

The http plugin isn't found also.

**Comment by janspeller** [comment]
Do you run boswatch as root?
`sudo pip3 install python-telegram-bot`
might help

**Comment by dernippel** [comment]
installing the bot using pip3 ha worked. Thank you for the quick help.

Running boswatch as root seems not to be neccesarry. I created a systemuser with "sudo adduser boswatch --no-create-home --disabled-login --shell /bin/false" and changed permissions with "sudo chown -R boswatch:boswatch /opt/boswatch3". It seems to work very well. However its not possible to bind ports in the range from 1 - 1024 without running as root.

**Comment by janspeller** [comment]
This is probably a topic for another issue as this issue is resolved
