### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by firestation-csi** [BOSWatch/BW3-Core#83]
Server Start bricht mit:  `routerManager   [ERROR   ] plugin not found: http` ab.
Config wurde laut Plugin Beispiel angelegt.

**Comment by samazaphikel** [comment]
Vorher das Update ordentlich durchgeführt?

Bzw. wie das Update durchgeführt.

ist die mysql.py angelegt worden?

**Comment by firestation-csi** [comment]
Boswatch3 wurde komplett neu mit dem Install Script eingerichtet. Wird in der Server-Config das http Plugin auskommentiert läuft der Server.

**Comment by samazaphikel** [comment]
Welche Version wurde installiert?
Zeig mal dein Logfile und Config file.

RICs und Frequenzen aus Xen

**Comment by firestation-csi** [comment]
Client Version: 3.0.0
Server Version 3.0.0

Server und Client .yaml hab ich hier umbenannt (Upload im GitHub nicht möglich)

[client.log](https://github.com/BOSWatch/BW3-Core/files/6156422/client.log)
[server.log](https://github.com/BOSWatch/BW3-Core/files/6156423/server.log)
[client.txt](https://github.com/BOSWatch/BW3-Core/files/6156428/client.txt)
[server.txt](https://github.com/BOSWatch/BW3-Core/files/6156429/server.txt)

**Comment by samazaphikel** [comment]
Ich habe zvei nicht in Verwendung und kann so auf Anhieb keinen Fehler sehen können.

Ich kann heute Abend nochmal auf dem PC nachschauen, da kann man das doch etwas besser lesen wie auf dem Smartphone.

evtl. antwortet bis dahin noch jemand

**Comment by Schrolli91** [comment]
Externe Libs installiert? Siehe Docs: https://docs.boswatch.de/plugin/http.html#externe-abhangigkeiten

Externe Abhängigkeiten
- asyncio
- aiohttp

@janspeller war das der Bug den du meintest, dass hier die Fehlermeldung irreführend ist?

@firestation-csi Wenn du den dev Branch installierst, sollte die Fehlermeldung eindeutiger sein, das sollte nämlich dort schon gefixt sein. Aber ich gehe wie gesagt von den fehlenden Abhängigkeiten aus.

**Comment by firestation-csi** [comment]
Servus Schrolli91,
wurde beides bereits per pip installiert.
Gruß

**Comment by firestation-csi** [comment]
Fehler gefunden!
aiohttp sollte nicht per pip installiert werden.
--> sudo apt-get install python3-aiohttp

Vielen Dank für Eure Hilfe

**Comment by janspeller** [comment]
> @janspeller war das der Bug den du meintest, dass hier die Fehlermeldung irreführend ist?

Jo, das ist genau der Fehler.

**Comment by janspeller** [comment]
> Fehler gefunden!
> 
> aiohttp sollte nicht per pip installiert werden.
> 
> --> sudo apt-get install python3-aiohttp
> 
> 
> 
> Vielen Dank für Eure Hilfe

Da hätte es vermutlich auch ein install im User, den du für Boswatch verwendest, getan ;)

**Comment by samazaphikel** [comment]
Externe Anwendung, sollte man eig. sowieso auf Environment laufen lassen.
