### ISSUE TITLE
[WIEDER ONLINE] Website und Dokumentation offline?

### ISSUE THREAD

**Issue by MorrisBrProjects** [BOSWatch/BW3-Core#95]
Warum ist die seite: https://bwcc.boswatch.de/ aus? und die docs?

**Comment by Schrolli91** [comment]
Der Server auf welchem die Homepage lief wurde nicht verlängert.
Aktuell läuft im Hintergrund ein Umzug auf einen Neuen Server.
Leider bin ich zeitlich aktuell komplett ausgelastet - da gehen im Moment andere Dinge vor.
Hoffe wir kommen zeitnah wieder online.

**Comment by theMagicKnight** [comment]
falls erwünscht sonst gerne löschen.

http://boswatch.landofpixel.de
habe ich schnell ein board drauf gespielt

Lars

**Comment by jonasled** [comment]
Ich habe ( zumindestens temporär ) die Dokumentation bei mir aufgesetzt, sodass sie solange die offizielle offline ist trotzdem noch erreichbar ist: https://jonasled.pages.gitlab.jonasled.de/boswatch-3-docs/

**Comment by theMagicKnight** [comment]
ja das könnte man alles auf meine subdomain laden und hinten dran noch das bb3 forum.

**Comment by janspeller** [comment]
@Schrolli91 Wenn hier Server-Ressourcen fehlen könnte ich auch gerne etwas bereitstellen, inklusive Mattermost Server

**Comment by jonasled** [comment]
Resourcen hätte ich auch noch genügend übrig, die ich gerne zur Verfügung stelle.

**Comment by Schrolli91** [comment]
@janspeller ich könnte dir den Dump (Backup kurz vor Offlinestellung) von der alten MM Instanz bereitstellen.

**Comment by janspeller** [comment]
> @janspeller ich könnte dir den Dump (Backup kurz vor Offlinestellung) von der alten MM Instanz bereitstellen.

Das wäre glaube ich nicht schlecht, würde dann eine Instanz aufsetzen. Kommunikation bzgl. DNS und Dump über Email? ([jan@speller.biz](mailto:jan@speller.biz))

**Comment by Schrolli91** [comment]
Ich melde mich - Danke derweil

**Comment by janspeller** [comment]
@Schrolli91 Die DNS-Anpassung ist durch, bwcc.boswatch.de funktioniert wieder :)
Ich sehe die Tage noch zu, dass ich den Redirect der Root-Url (auf das BW3-Core Repo) und die Dokumentation hin bekomme.

Dokumentation wäre eventuell was für Github pages oder? :)

**Comment by janspeller** [comment]
Außerdem müsste ich noch einen Mailserver einrichten, der die Mails für Mattermost versendet.

**Comment by janspeller** [comment]
@Schrolli91 Email-Versand wollte ich gestern einrichten, da ich eh auf mailcow umgestellt habe, läuft aber wohl noch über einen alten mailserver von dir, ist das möglich? :D

**Comment by Schrolli91** [comment]
Das kannst du raus hauen. Diese Domain gibt es in wenigen Wochen nicht mehr.

**Comment by janspeller** [comment]
Baue ich bei gelegenheit in den naechsten tagen um 👍
